#ifndef ENGINE_MOUSE_H
#define ENGINE_MOUSE_H

enum MouseButton
{
	MOUSEBUTTON_UNKNOWN,
	MOUSEBUTTON_LEFT,
	MOUSEBUTTON_RIGHT,
	MOUSEBUTTON_MIDDLE,
	MOUSEBUTTON_BUTTON4,
	MOUSEBUTTON_BUTTON5,
	MOUSEBUTTON_COUNT,
};
#endif